#!/bin/sh

set -eu
F="${0%.sh}_sh.go"
trap "rm -f '$F~'" EXIT
exec > "$F~"

cat <<EOT
package ${GOPACKAGE:-types}

//go:generate $0${1:+ $*}

// Code generated by $0. DO NOT EDIT.

import (
	"bazil.org/fuse"
	"bazil.org/fuse/fs"
)
EOT

generate_alias() {
	local t="$1" pkg="$2" n=
	shift 2

	for n; do
		cat <<EOT

// $n is a proxy to the standard $pkg.$n ${t#*:}
${t%:*} $n = $pkg.$n
EOT
	done

}

generate_const() {
	generate_alias const:constant "$@"
}

generate_types() {
	generate_alias type "$@"
}

generate_types fuse \
	Attr

generate_types fs \
	Node

generate_const fuse \
	ENOSYS

if ! diff -u "$F" "$F~" >&2; then
	mv "$F~" "$F"
fi
