package types

//go:generate ./fuse.sh

// Code generated by ./fuse.sh. DO NOT EDIT.

import (
	"bazil.org/fuse"
	"bazil.org/fuse/fs"
)

// Attr is an alias of the standard fuse.Attr type
type Attr = fuse.Attr

// Node is an alias of the standard fs.Node type
type Node = fs.Node

// ENOSYS is an alias of the standard fuse.ENOSYS constant
const ENOSYS = fuse.ENOSYS
