#!/bin/sh

set -eu
F="${0%.sh}_sh.go"
trap "rm -f '$F~'" EXIT
exec > "$F~"

cat <<EOT
package ${GOPACKAGE:-types}

//go:generate $0${1:+ $*}

// Code generated by $0. DO NOT EDIT.

import (
	"bazil.org/fuse"
	"bazil.org/fuse/fs"
)
EOT

generate_alias() {
	local t="$1" pkg="$2" n=
	shift 2

	if [ $# -gt 1 ]; then
		cat <<EOT

${t#*:} (
EOT
		for n; do
			cat <<EOT
	// $n is an alias of the standard $pkg.$n ${t#*:}
	$n = ${pkg##*/}.$n
EOT
		done
		cat <<EOT
)
EOT
	elif [ $# -eq 1 ]; then
		n="$1"
		cat <<EOT

// $n is an alias of the standard $pkg.$n ${t#*:}
${t%:*} $n = ${pkg##*/}.$n
EOT
	fi
}

generate_const() {
	generate_alias const:constant "$@"
}

generate_types() {
	generate_alias type "$@"
}

generate_types bazil.org/fuse \
	Attr

generate_types bazil.org/fuse/fs \
	Node

generate_const bazil.org/fuse \
	ENOSYS

if ! diff -u "$F" "$F~" >&2; then
	mv "$F~" "$F"
fi
