#!/bin/sh

set -eu
F="${0%.sh}_sh.go"
trap "rm -f '$F~'" EXIT
exec > "$F~"

cat <<EOT
package ${GOPACKAGE:-types}

//go:generate $0${1:+ $*}

// Code generated by $0. DO NOT EDIT.

import (
	"syscall"

	"bazil.org/fuse"
)
EOT

generate_wrapped_alias() {
	local t="$1" pkg="$2" f="$3" n=
	shift 3

	if [ $# -gt 1 ]; then
		cat <<EOT

${t%:*} (
EOT
		for n; do
			cat <<EOT
	// $n is a wrapped alias of the standard $pkg.$n ${t#*:}
	$n = $f(${pkg##*/}.$n)
EOT
		done
		cat <<EOT
)
EOT
	elif [ $# -eq 1 ]; then
		n="$1"
		cat <<EOT

// $n is a wrapped alias of the standard $pkg.$n ${t#*:}
${t%:*} $n = $f(${pkg##*/}.$n)
EOT
	fi
}

generate_wrapped_const() {
	generate_wrapped_alias "const:constant" "$@"
}

generate_wrapped_const syscall fuse.Errno \
	ENOENT \
	ENOSYS \
	ENOTDIR \

if ! diff -u "$F" "$F~" >&2; then
	mv "$F~" "$F"
fi
