package types

//go:generate ./syscall.sh

// Code generated by ./syscall.sh. DO NOT EDIT.

import (
	"syscall"

	"bazil.org/fuse"
)

const (
	// ENOENT is a wrapped alias of the syscall.ENOENT constant.
	ENOENT = fuse.Errno(syscall.ENOENT)
	// ENOSYS is a wrapped alias of the syscall.ENOSYS constant.
	ENOSYS = fuse.Errno(syscall.ENOSYS)
	// ENOTDIR is a wrapped alias of the syscall.ENOTDIR constant.
	ENOTDIR = fuse.Errno(syscall.ENOTDIR)
)
