package types

//go:generate ./syscall.sh

// Code generated by ./syscall.sh. DO NOT EDIT.

import (
	"syscall"

	"bazil.org/fuse"
)

const (
	// ENOENT is a wrapped alias of the syscall.ENOENT constant,
	// see https://pkg.go.dev/syscall#ENOENT for details.
	ENOENT = fuse.Errno(syscall.ENOENT)
	// ENOSYS is a wrapped alias of the syscall.ENOSYS constant,
	// see https://pkg.go.dev/syscall#ENOSYS for details.
	ENOSYS = fuse.Errno(syscall.ENOSYS)
	// ENOTDIR is a wrapped alias of the syscall.ENOTDIR constant,
	// see https://pkg.go.dev/syscall#ENOTDIR for details.
	ENOTDIR = fuse.Errno(syscall.ENOTDIR)
)
