package fuse

//go:generate ./fuse.sh

// Code generated by ./fuse.sh. DO NOT EDIT.

import (
	"bazil.org/fuse"
)

// AllowDev is a proxy function to bazil.org/fuse.AllowDev(),
// see https://pkg.go.dev/bazil.org/fuse#AllowDev for details.
func AllowDev() fuse.MountOption {
	return fuse.AllowDev()
}

// AllowNonEmptyMount is a proxy function to bazil.org/fuse.AllowNonEmptyMount(),
// see https://pkg.go.dev/bazil.org/fuse#AllowNonEmptyMount for details.
func AllowNonEmptyMount() fuse.MountOption {
	return fuse.AllowNonEmptyMount()
}

// AllowOther is a proxy function to bazil.org/fuse.AllowOther(),
// see https://pkg.go.dev/bazil.org/fuse#AllowOther for details.
func AllowOther() fuse.MountOption {
	return fuse.AllowOther()
}

// AllowSUID is a proxy function to bazil.org/fuse.AllowSUID(),
// see https://pkg.go.dev/bazil.org/fuse#AllowSUID for details.
func AllowSUID() fuse.MountOption {
	return fuse.AllowSUID()
}

// AsyncRead is a proxy function to bazil.org/fuse.AsyncRead(),
// see https://pkg.go.dev/bazil.org/fuse#AsyncRead for details.
func AsyncRead() fuse.MountOption {
	return fuse.AsyncRead()
}

// CongestionThreshold is a proxy function to bazil.org/fuse.CongestionThreshold(),
// see https://pkg.go.dev/bazil.org/fuse#CongestionThreshold for details.
func CongestionThreshold(n uint16) fuse.MountOption {
	return fuse.CongestionThreshold(n)
}

// DaemonTimeout is a proxy function to bazil.org/fuse.DaemonTimeout(),
// see https://pkg.go.dev/bazil.org/fuse#DaemonTimeout for details.
func DaemonTimeout(name string) fuse.MountOption {
	return fuse.DaemonTimeout(name)
}

// DefaultPermissions is a proxy function to bazil.org/fuse.DefaultPermissions(),
// see https://pkg.go.dev/bazil.org/fuse#DefaultPermissions for details.
func DefaultPermissions() fuse.MountOption {
	return fuse.DefaultPermissions()
}

// FSName is a proxy function to bazil.org/fuse.FSName(),
// see https://pkg.go.dev/bazil.org/fuse#FSName for details.
func FSName(name string) fuse.MountOption {
	return fuse.FSName(name)
}

// LockingFlock is a proxy function to bazil.org/fuse.LockingFlock(),
// see https://pkg.go.dev/bazil.org/fuse#LockingFlock for details.
func LockingFlock() fuse.MountOption {
	return fuse.LockingFlock()
}

// LockingPOSIX is a proxy function to bazil.org/fuse.LockingPOSIX(),
// see https://pkg.go.dev/bazil.org/fuse#LockingPOSIX for details.
func LockingPOSIX() fuse.MountOption {
	return fuse.LockingPOSIX()
}

// MaxBackground is a proxy function to bazil.org/fuse.MaxBackground(),
// see https://pkg.go.dev/bazil.org/fuse#MaxBackground for details.
func MaxBackground(n uint16) fuse.MountOption {
	return fuse.MaxBackground(n)
}

// MaxReadahead is a proxy function to bazil.org/fuse.MaxReadahead(),
// see https://pkg.go.dev/bazil.org/fuse#MaxReadahead for details.
func MaxReadahead(n uint32) fuse.MountOption {
	return fuse.MaxReadahead(n)
}

// ReadOnly is a proxy function to bazil.org/fuse.ReadOnly(),
// see https://pkg.go.dev/bazil.org/fuse#ReadOnly for details.
func ReadOnly() fuse.MountOption {
	return fuse.ReadOnly()
}

// Subtype is a proxy function to bazil.org/fuse.Subtype(),
// see https://pkg.go.dev/bazil.org/fuse#Subtype for details.
func Subtype(fstype string) fuse.MountOption {
	return fuse.Subtype(fstype)
}

// WritebackCache is a proxy function to bazil.org/fuse.WritebackCache(),
// see https://pkg.go.dev/bazil.org/fuse#WritebackCache for details.
func WritebackCache() fuse.MountOption {
	return fuse.WritebackCache()
}

// MountOption is an alias of the fuse.MountOption type.
type MountOption = fuse.MountOption
